### ISSUE TITLE
Some LP NFTs doesn't load

### ISSUE THREAD

**Issue by Jorropo** [Uniswap/uniswap-interface#1971]
**Bug Description**
The NFT keeps loading forever and never loads.

**Steps to Reproduce**

Open https://app.uniswap.org/#/pool/50678

**Expected Behavior**
The NFT should be shown.

**Credit**
Initially reported to me by `Bing²` and `alshady` in the uniswap github.

**Comment by moodysalem** [comment]
it's a new bug and fixed in https://github.com/Uniswap/uniswap-interface/commit/c52cd2c38ee0155bacc97cd91fc56e1dff32a07e

thanks for reporting

**Comment by roromi13** [comment]
Issue is still not fixed

**Comment by Rachel-Eichenberger** [comment]
I am still seeing this issue in Both Chrome and Firefox (on this pool)

**Comment by moodysalem** [comment]
we do daily releases, so it should be fixed in today's build
